# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
VERSION_TUPLE = tuple[int | str, ...] if TYPE_CHECKING else object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "0.1.dev1+g9f4e98a"
__version_tuple__ = version_tuple = (0, 1, "dev1", "g9f4e98a")
